name: User Info UTHMAN

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        default: "uthman"
      location:
        description: "Location"
        required: true
        default: "Ireland"
      age:
        description: "Age"
        required: true
        default: "33"

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        env:
          NAME: ${{ inputs.name }}
          LOCATION: ${{ inputs.location }}
          AGE: ${{ inputs.age }}
        run: |
          ls
          chmod +x ./script/uthman.sh
          ./script/uthamn.sh