name: User Info UTHMAN

on:
  workflow_dispatch:

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          ls
          chmod +x ./script/uthman.sh
          ./script/uthman.sh
